// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAISyjUKJWB-_C7_IsaGmvoyzCtds3t1ns',
    appId: '1:527698424343:web:70ee46fa20fd0afd4fe252',
    messagingSenderId: '527698424343',
    projectId: 'plastic-diver',
    authDomain: 'plastic-diver.firebaseapp.com',
    storageBucket: 'plastic-diver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNt9t3lLP33on_9JANKCJPoAPNR6mbHnw',
    appId: '1:527698424343:android:eb25c7d7627242294fe252',
    messagingSenderId: '527698424343',
    projectId: 'plastic-diver',
    storageBucket: 'plastic-diver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq4S7bhXpE4mBO83qUdR1hYAyQQqgaCYQ',
    appId: '1:527698424343:ios:df7ca579bf0c5e734fe252',
    messagingSenderId: '527698424343',
    projectId: 'plastic-diver',
    storageBucket: 'plastic-diver.appspot.com',
    iosBundleId: 'com.nomaddev.plasticdiver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq4S7bhXpE4mBO83qUdR1hYAyQQqgaCYQ',
    appId: '1:527698424343:ios:df7ca579bf0c5e734fe252',
    messagingSenderId: '527698424343',
    projectId: 'plastic-diver',
    storageBucket: 'plastic-diver.appspot.com',
    iosBundleId: 'com.nomaddev.plasticdiver',
  );
}
